[package]
name = "leetcode1417"
version = "0.1.0"
authors = ["NKcell <517343690@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
