"""
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    s_dict = {}
    for i in s:
        s_dict[i] = s_dict.get(i,1) + 1
    #print (s_dict)
    t_dict = {}
    for i in t:
        t_dict[i] = t_dict.get(i,1) + 1
    #print (t_dict)
    for key in t_dict:
        if s_dict.get(key,None) != t_dict[key]:
            return key


print (findTheDifference('abcd', 'abcde'))



# 又是对Counter的应用
"""
from collections import Counter

class Solution:
    def findTheDifference(self, s, t):
        dicts = Counter(s)
        dictt = Counter(t)
        commondict = dictt - dicts
        commondictChar = list(commondict.elements())
        return "".join(commondictChar)
"""

#帅气的想法
"""
class Solution:
    def findTheDifference(self, s, t):
        str='abcdefghijklmnopqrstuvwxyz'
        for item in str:
            if len(s.split(item))!=len(t.split(item)):
                return item
"""